### ISSUE TITLE
pixnet.js 可考慮加上移除蓋板廣告的 Code

### ISSUE THREAD

**Issue by wildskyf** [puritys/tampermonkeyScript#1]
div id: ad-full-page

**Comment by puritys** [comment]
你可以安裝 adblock extension 來移除蓋板廣告

**Comment by wildskyf** [comment]
我有裝，廣告會移除，但上面提到的那個 div
不會，所以會變成一塊半透明的黑遮罩擋住整個畫面，什麼都不能點很不方便，我自己是有補下面這段，只是剛好看到你也有寫 pixnet
script，所以來建議一下XD


document.querySelector('#ad-full-page').remove();

**Comment by puritys** [comment]
謝謝你建議，不過我沒有裝 adblock ，沒碰到這個問題， 而且我很少看 pixnet ，只是偶爾要 copy pixnet 上餐廳的地址時很不方便，才寫了這個簡單的 script.

**Comment by puritys** [comment]
https://github.com/puritys/tampermonkeyScript/commit/6747b4270a3385365671626da665e44ede7da266

**Comment by wildskyf** [comment]
蓋版廣告實在很煩人 :S
